### ISSUE TITLE
Last three items in hourly are null

### ISSUE THREAD

**Issue by noblecloud** [open-meteo/open-meteo#71] opened 2022-07-20 14:06 UTC
The last three hours of all hourly requests are null for all fields except time. 

Request URL: https://api.open-meteo.com/v1/forecast?latitude=38.8921&longitude=-77.0241&hourly=temperature_2m&current_weather=true&timezone=America%2FNew_York

```json
{
  "latitude": 38.875,
  "longitude": -77,
  "generationtime_ms": 0.29289722442626953,
  "utc_offset_seconds": -14400,
  "elevation": 5,
  "current_weather": {
    "temperature": 29.3,
    "windspeed": 6.7,
    "winddirection": 286,
    "weathercode": 0,
    "time": "2022-07-20T10:00"
  },
  "hourly_units": {
    "time": "iso8601",
    "temperature_2m": "°C"
  },
  "hourly": {
    "time": [
      "2022-07-20T00:00",
      "2022-07-20T01:00",
      "2022-07-20T02:00",
      "2022-07-20T03:00",
      "2022-07-20T04:00",
      "2022-07-20T05:00",
      "2022-07-20T06:00",
      "2022-07-20T07:00",
      "2022-07-20T08:00",
      "2022-07-20T09:00",
      "2022-07-20T10:00",
      "2022-07-20T11:00",
      "2022-07-20T12:00",
      "2022-07-20T13:00",
      "2022-07-20T14:00",
      "2022-07-20T15:00",
      "2022-07-20T16:00",
      "2022-07-20T17:00",
      "2022-07-20T18:00",
      "2022-07-20T19:00",
      "2022-07-20T20:00",
      "2022-07-20T21:00",
      "2022-07-20T22:00",
      "2022-07-20T23:00",
      "2022-07-21T00:00",
      "2022-07-21T01:00",
      "2022-07-21T02:00",
      "2022-07-21T03:00",
      "2022-07-21T04:00",
      "2022-07-21T05:00",
      "2022-07-21T06:00",
      "2022-07-21T07:00",
      "2022-07-21T08:00",
      "2022-07-21T09:00",
      "2022-07-21T10:00",
      "2022-07-21T11:00",
      "2022-07-21T12:00",
      "2022-07-21T13:00",
      "2022-07-21T14:00",
      "2022-07-21T15:00",
      "2022-07-21T16:00",
      "2022-07-21T17:00",
      "2022-07-21T18:00",
      "2022-07-21T19:00",
      "2022-07-21T20:00",
      "2022-07-21T21:00",
      "2022-07-21T22:00",
      "2022-07-21T23:00",
      "2022-07-22T00:00",
      "2022-07-22T01:00",
      "2022-07-22T02:00",
      "2022-07-22T03:00",
      "2022-07-22T04:00",
      "2022-07-22T05:00",
      "2022-07-22T06:00",
      "2022-07-22T07:00",
      "2022-07-22T08:00",
      "2022-07-22T09:00",
      "2022-07-22T10:00",
      "2022-07-22T11:00",
      "2022-07-22T12:00",
      "2022-07-22T13:00",
      "2022-07-22T14:00",
      "2022-07-22T15:00",
      "2022-07-22T16:00",
      "2022-07-22T17:00",
      "2022-07-22T18:00",
      "2022-07-22T19:00",
      "2022-07-22T20:00",
      "2022-07-22T21:00",
      "2022-07-22T22:00",
      "2022-07-22T23:00",
      "2022-07-23T00:00",
      "2022-07-23T01:00",
      "2022-07-23T02:00",
      "2022-07-23T03:00",
      "2022-07-23T04:00",
      "2022-07-23T05:00",
      "2022-07-23T06:00",
      "2022-07-23T07:00",
      "2022-07-23T08:00",
      "2022-07-23T09:00",
      "2022-07-23T10:00",
      "2022-07-23T11:00",
      "2022-07-23T12:00",
      "2022-07-23T13:00",
      "2022-07-23T14:00",
      "2022-07-23T15:00",
      "2022-07-23T16:00",
      "2022-07-23T17:00",
      "2022-07-23T18:00",
      "2022-07-23T19:00",
      "2022-07-23T20:00",
      "2022-07-23T21:00",
      "2022-07-23T22:00",
      "2022-07-23T23:00",
      "2022-07-24T00:00",
      "2022-07-24T01:00",
      "2022-07-24T02:00",
      "2022-07-24T03:00",
      "2022-07-24T04:00",
      "2022-07-24T05:00",
      "2022-07-24T06:00",
      "2022-07-24T07:00",
      "2022-07-24T08:00",
      "2022-07-24T09:00",
      "2022-07-24T10:00",
      "2022-07-24T11:00",
      "2022-07-24T12:00",
      "2022-07-24T13:00",
      "2022-07-24T14:00",
      "2022-07-24T15:00",
      "2022-07-24T16:00",
      "2022-07-24T17:00",
      "2022-07-24T18:00",
      "2022-07-24T19:00",
      "2022-07-24T20:00",
      "2022-07-24T21:00",
      "2022-07-24T22:00",
      "2022-07-24T23:00",
      "2022-07-25T00:00",
      "2022-07-25T01:00",
      "2022-07-25T02:00",
      "2022-07-25T03:00",
      "2022-07-25T04:00",
      "2022-07-25T05:00",
      "2022-07-25T06:00",
      "2022-07-25T07:00",
      "2022-07-25T08:00",
      "2022-07-25T09:00",
      "2022-07-25T10:00",
      "2022-07-25T11:00",
      "2022-07-25T12:00",
      "2022-07-25T13:00",
      "2022-07-25T14:00",
      "2022-07-25T15:00",
      "2022-07-25T16:00",
      "2022-07-25T17:00",
      "2022-07-25T18:00",
      "2022-07-25T19:00",
      "2022-07-25T20:00",
      "2022-07-25T21:00",
      "2022-07-25T22:00",
      "2022-07-25T23:00",
      "2022-07-26T00:00",
      "2022-07-26T01:00",
      "2022-07-26T02:00",
      "2022-07-26T03:00",
      "2022-07-26T04:00",
      "2022-07-26T05:00",
      "2022-07-26T06:00",
      "2022-07-26T07:00",
      "2022-07-26T08:00",
      "2022-07-26T09:00",
      "2022-07-26T10:00",
      "2022-07-26T11:00",
      "2022-07-26T12:00",
      "2022-07-26T13:00",
      "2022-07-26T14:00",
      "2022-07-26T15:00",
      "2022-07-26T16:00",
      "2022-07-26T17:00",
      "2022-07-26T18:00",
      "2022-07-26T19:00",
      "2022-07-26T20:00",
      "2022-07-26T21:00",
      "2022-07-26T22:00",
      "2022-07-26T23:00"
    ],
    "temperature_2m": [
      25.6,
      25,
      25,
      24.7,
      24.4,
      24,
      23.7,
      24,
      26.1,
      28,
      29.3,
      30.5,
      31.5,
      32.3,
      33.1,
      33.5,
      33.9,
      33.8,
      33.6,
      33,
      31.5,
      29.3,
      28.3,
      27.4,
      27,
      26.9,
      26.6,
      26.1,
      25.5,
      25.1,
      24.8,
      24.9,
      25.8,
      27.3,
      28.9,
      30.8,
      32.6,
      32.7,
      33.6,
      34.7,
      34.7,
      34.7,
      33.8,
      33,
      31.9,
      30.9,
      30,
      29.3,
      28.3,
      27.3,
      26.6,
      26.1,
      25.6,
      24.9,
      24.4,
      24.5,
      26.3,
      28.1,
      29.6,
      30.9,
      32,
      33,
      33.8,
      34.5,
      34.9,
      35,
      34.7,
      34,
      32.3,
      30.3,
      29.3,
      28.5,
      27.7,
      26.6,
      26.3,
      26.1,
      25.8,
      25.4,
      24.8,
      24.7,
      26.5,
      28.1,
      30.3,
      32.8,
      34,
      34.8,
      35.6,
      36.1,
      36.3,
      36.1,
      35.6,
      34.9,
      33.5,
      32.2,
      30.7,
      28.9,
      28.1,
      27.4,
      26.7,
      26.2,
      25.8,
      25.7,
      25.8,
      26.2,
      27.4,
      29.1,
      31.3,
      33.9,
      35.5,
      36.9,
      38.3,
      38.9,
      39.2,
      39.1,
      38.5,
      37.5,
      35.8,
      34.2,
      32.3,
      30.3,
      29.7,
      29.6,
      29.7,
      28.8,
      28.3,
      27.7,
      27.6,
      27.5,
      28.1,
      29.2,
      30.8,
      32.9,
      34.4,
      36,
      37.1,
      36.7,
      35.5,
      33.9,
      33.3,
      32.8,
      31.9,
      30.6,
      29.2,
      27.5,
      26.9,
      26.6,
      26.2,
      25.9,
      25.7,
      25.3,
      24.7,
      24,
      23.4,
      23.5,
      24,
      24.8,
      25.6,
      26.5,
      27.4,
      27.6,
      27.5,
      27.1,
      26.8,
      26.3,
      25.8,
      null,
      null,
      null
    ]
  }
}
```

**Comment by open-meteo** [comment] 2022-07-23 09:03
Hi @noblecloud,

I believe the issue might be caused by one failed model-update. Right now, data seems fine. Model update failures happen roughly once every 2 months. 

I suspect however there might be more issues, because with increasing timezone offsets, the issue is getting bigger. I might consider to change the time selection a bit to hold back with immediately showing 7 days starting from exactly `today`.

In this case, until 2:00 in the morning, the API would return data starting at `yesterday`. 

I guess this could be viable workaround for those rare cases of model update failures

What do you think?

Best, Jeff

**Comment by patrick-zippenfenig** [comment] 2023-04-05 10:41
Closing for cleanup. Feel free to reopen if you have more questions

**Closed by patrick-zippenfenig** 2023-04-05 10:41 UTC
