### ISSUE TITLE
Glitch in 'seamless' data for MeteoFrance

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#173] opened 2022-12-06 09:10 UTC
Hopefully the glitch should be apparent from the following:

![image](https://user-images.githubusercontent.com/9009792/205864097-bc9be09f-d01e-4096-a2b8-736f12f07735.png)

This is for the following request:

https://open-meteo.com/en/docs#latitude=45.18&longitude=5.71&hourly=temperature_2m&models=meteofrance_seamless,meteofrance_arpege_europe,meteofrance_arome_france

**Comment by drmrbrewer** [comment] 2022-12-06 09:26
Incidentally, the graph seems to differ slightly to that shown e.g. [here](https://www.meteociel.fr/previsions-arpege-1h/13358/grenoble.htm):

![image](https://user-images.githubusercontent.com/9009792/205870341-210d9ecc-0f2b-4ed8-b8f6-b85064f1e38d.png)

The overall form seems the same, but open-meteo is higher by around 1C or so.  Perhaps this is due to [automatic correction for elevation](https://openmeteo.substack.com/p/improving-weather-forecasts-with)?  The [return data](https://api.open-meteo.com/v1/forecast?latitude=45.18&longitude=5.71&hourly=temperature_2m&models=meteofrance_seamless,meteofrance_arpege_europe,meteofrance_arome_france) does include the elevation (218m) but it would be interesting to know what temperature correction (if any) has been applied.

Incidentally (no. 2), why is there a long series of `null` values in the return data?  I can understand if you're returning data for multiple models having different amounts of data, but it happens even when asking for data from a [single model](https://api.open-meteo.com/v1/forecast?latitude=45.18&longitude=5.71&hourly=temperature_2m&models=meteofrance_seamless).

**Comment by patrick-zippenfenig** [comment] 2022-12-07 18:45
The jump at the end is caused by the `ARPEGE World` model... I am surprised that `ARPEGE Europe` and `World` are so much apart. "Technically" everything seems correct, but ARPEGE model data is just off

The temperature difference looks reasonable for elevation correction.

![Screenshot 2022-12-07 at 19 32 31](https://user-images.githubusercontent.com/11670456/206266471-c09a57a3-fd25-4c80-aca9-90d0595103ed.png)

`Best Match` is mixing AROME and ICON-EU+Global and seems to produce stable results

![Screenshot 2022-12-07 at 19 42 50](https://user-images.githubusercontent.com/11670456/206268421-dfe36a14-0d57-4064-9b70-a97202c90271.png)


The trailing `null` values in each data array ensure that they all have the same number of elements. Arguably they could be shortened, but working with the same length makes it easier :)

**Comment by drmrbrewer** [comment] 2022-12-07 20:26
Wow, `arpege_world` (black) and `arpege_europe` (green) are way off each other... around 10C apart from 8 to 9 Dec and it doesn't close up much for a couple of days after that `:-0`

In fact the whole thing is a bit of a mess (not your fault!) because `arome` seems to meander from `world` to `europe` around the 9 Dec mark.

So, as a result, the "glitch" as I called it is more just a reflection of some pretty weird data from meteofrance.

Understood about the `null` values... so you just pad out to fill up to the max time possible across all models?  Is there any particular reason for this?  Rather than just filling out the `time` array to the max, and the various data arrays just up to what is available (with `null` assumed thereafter)?  I suppose I shouldn't be too precious about fetching redundant data, but it seems slightly inefficient :-)   It's really not a big deal because it's easy enough to deal with, but I'm just curious.

**Comment by patrick-zippenfenig** [comment] 2022-12-08 14:19
Elevation correction only applies a fixed temperature offset (0.65°C per 100 m). I think the differences are caused by different model dynamics for complex terrain.

Even with more complex downscaling (additional physical models) I do not think it is possible to correct those issues.

It is good to know that the issues are less dominant for other close by locations

**Comment by patrick-zippenfenig** [comment] 2023-04-05 10:26
Closing for cleanup. Feel free to reopen if you have more questions

**Closed by patrick-zippenfenig** 2023-04-05 10:26 UTC
