### ISSUE TITLE
Comma URL encoding

### ISSUE THREAD

**Issue by DadiBit** [open-meteo/open-meteo#1012] opened 2024-09-11 19:18 UTC
The documentation suggests using a comma to pass lists, however the `,` character should be URL encoded.

It's encoded by default from the Kotlin multiplatform Ktor library (yep, I'm getting back to developing the kmp sdk!), and causes an error:

```shell
$ curl "https://api.open-meteo.com/v1/elevation?latitude=0%2C50&longitude=10,15"
{"reason":"Value was not of type 'Float' at path 'latitude.0'. Data found at 'latitude.0' was not Float.","error":true}
```

Using explicit `,` works:

```shell
$ curl "https://api.open-meteo.com/v1/elevation?latitude=0,50&longitude=10,15" 
{"elevation":[31.0, 259.0]}
```

Tested "list" parameters of other APIs that do not have this bug (`%2C` can be used instead of `,`):

- Latitude/longitude Forecast
- Hourly Forecast
- Daily Forecast
- Hourly Historical Forecast
- Daily Historical Forecast
- Hourly Historical
- Daily Historical
- Hourly Ensemble
- Models Ensemble
- Daily Climate Change
- Models Climate Change
- Hourly Marine
- Daily Marine
- Hourly Air Quality

I didn't check other "list" properties, as well as specific forecast APIs, but for the time being I suggest looking into the elevation API source code. Something is handled differently (probably the string isn't URL decoded) from all other APIs.

**Comment by patrick-zippenfenig** [comment] 2024-09-16 07:25
Thanks for the report. The issue is based in the underlaying HTTP library to parse parameters. For `hourly` or `daily` weather parameters I implemented workaround, but not for coordinates. I will have a look to find a more generic solution in the next weeks.

**Comment by DadiBit** [comment] 2024-09-16 13:55
I'm sorry. Maybe I misunderstood you, however I wanted to say that both the Forecast and Climate Change APIs work fine when using `%2C` encoded commas for multiple locations ([https://climate-api.open-meteo.com/v1/climate?latitude=45.6495%2C45.5946&longitude=13.7768%2C10.7115&...](https://climate-api.open-meteo.com/v1/climate?latitude=45.6495%2C45.5946&longitude=13.7768%2C10.7115&start_date=2000-01-01&end_date=2000-01-31&models=CMCC_CM2_VHR4,FGOALS_f3_H,HiRAM_SIT_HR,MRI_AGCM3_2_S,EC_Earth3P_HR,MPI_ESM1_2_XR,NICAM16_8S&daily=temperature_2m_max) works)

I also tried to replace `.` with `%2E` and both elevation and forecast APIs parse the float(s) correctly.

I'm probably wrong (I don't really know Swift), however I suspect it's near where the response is generated and returned:
https://github.com/open-meteo/open-meteo/blob/9bbcc2c035ef2e4039d35c02944e1e2f8e0c1449/Sources/App/Dem/DemController.swift#L41

**Comment by patrick-zippenfenig** [comment] 2024-09-19 08:19
Thanks, got it. I will fix it soon.

**Comment by patrick-zippenfenig** [comment] 2024-09-19 08:20
Fixed in https://github.com/open-meteo/open-meteo/commit/e14427ed5e44d4cc9a3a99fdcdad7860f58bfdb6. Will be deployed in the next days

**Closed by patrick-zippenfenig** 2024-09-19 08:20 UTC

**Comment by DadiBit** [comment] 2024-09-19 09:06
Thank you. You are amazing (as usual)!
