### ISSUE TITLE
Incorrect elevation for `elevation=nan` (should return (native) grid-cell height)

### ISSUE THREAD

**Issue by fzeiser** [open-meteo/open-meteo#1155] opened 2024-12-10 07:55 UTC
Thank you very much for your great product! We've encountered a bug in the API response for  `elevation=nan`, i.e. when we want to use the weather models native grid cell height.

The API documentation for elevation states the following:
> The elevation used for statistical downscaling. Per default, a [90 meter digital elevation model is used](https://openmeteo.substack.com/p/improving-weather-forecasts-with). You can manually set the elevation to correctly match mountain peaks. **If `&elevation=nan` is specified, downscaling will be disabled and the API uses the average grid-cell height.** For multiple locations, elevation can also be comma separated.

**Example request**:
Era5 air-temperatures for for a point in the swiss mointains, so the elevation is certainly not 0. 

https://archive-api.open-meteo.com/v1/archive?latitude=46.6344&longitude=8.4382&start_date=2024-11-28&end_date=2024-11-29&hourly=temperature_2m&models=era5&elevation=nan

Requested point: lat=46.6, lon=8.4 (-> will receive nearest neighbor)
![image](https://github.com/user-attachments/assets/97d040b1-2826-45f2-a936-402b3a9e5562)

**Response**:
```
{
  "latitude": 46.75,
  "longitude": 8.5,
  "generationtime_ms": 0.0439882278442383,
  "utc_offset_seconds": 0,
  "timezone": "GMT",
  "timezone_abbreviation": "GMT",
  "elevation": 0,        # --- Elevation in the alps is certainly not 0! 
  "hourly_units": {
    "time": "iso8601",
    "temperature_2m": "°C"
  },
  "hourly": {
    "time": [
      "2024-11-28T00:00",
      "2024-11-28T01:00",
      [...]
    ],
    "temperature_2m": [-5.1, -4.4, -1.9, [...]]
  }
}
```

**Expected response**:
```
{....
elevation: 1831.92
...
```

**Further information**:   
- We've compared the temperatures to era5 downloaded separately. It seems like `elevation=nan`, as intended, does not apply a further statistical downscaling. So I only question the returned elevation. 
- If one uses the statistical downscaling, the returned elevation is `"elevation": 2785`.

**Comment by patrick-zippenfenig** [comment] 2024-12-10 13:47
Thanks for the report. I can confirm this is a bug and I will try to fix it soon

**Comment by patrick-zippenfenig** [comment] 2024-12-12 16:59
It takes a bit longer to fix this issue. It looks like the returned surface elevation data from the CDS API had an issue. Right now, I cannot debug it, because the CDS API did not return any data since 2 days.

**Comment by patrick-zippenfenig** [comment] 2024-12-13 08:58
Issue is now fixed!

**Closed by patrick-zippenfenig** 2024-12-13 08:58 UTC
Labels: bug

**Comment by felixmatt** [comment] 2024-12-18 11:47
@patrick-zippenfenig, thanks a lot for fixing the issue so fast! API response for `elevation=nan` contains now non-zero elevations. However, we encounter a significant difference when comparing the elevations from the api response with the elevations from era5 data downloaded as netCDFs from cds. The difference is about 20m for grid-cell elevations between 500-1200masl. We calculate the surface elevation from the `geopotential_at_surface` variable divided by the Earth's gravitational acceleration, g (=9.80665 m s-2), as recommended by ECMWF [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-pressure-levels?tab=overview#:~:text=The%20geopotential%20height%20can%20be%20calculated%20by%20dividing%20the%20geopotential%20by%20the%20Earth%27s%20gravitational%20acceleration%2C%20g%20(%3D9.80665%20m%20s%2D2).). Funfact: The elevations from the api response and netCDF are the same when using `g=10 m s-2` to calculate surface elevation from the `geopotential_at_surface` variable.

**Comment by patrick-zippenfenig** [comment] 2024-12-22 11:41
@felixmatt thanks for the check!

The ERA5 elevation is now corrected. A bit of background:
- In my first fix, I only restored the elevation file from backup, because I could not download data from the CDS API. The backup was roughly 2 years old and was apparently did not correctly applying the gravity constant (~end of 2022). 
- The actual bug was that due to larger refactoring for the new CDS API version, I forgot to shift and flip the grid to a starting point of -180°/-90°. This was not noticed for some weeks, because the download routines to do not download surface elevation height. It only got downloaded again, because I recently migrated ERA5 processing to a different set of servers.
- I now improved the code to automatically detect grids that need to be adjusted to an origin point of -90/-180. That will also remove code complexity in the future (once I actually refactor all the other downloaders :D)

**Comment by felixmatt** [comment] 2025-01-28 11:28
@patrick-zippenfenig, thanks for fixing and the detailed explanation. However, it seems like there is still sth wrong with elevations close to coastal regions, where the response from an api call does not provide the native era5 evelations. E.g. this call:

https://archive-api.open-meteo.com/v1/archive?latitude=71&longitude=25.75&start_date=2025-01-11&end_date=2025-01-25&hourly=temperature_2m&cell_selection=nearest&models=era5&elevation=NaN

where elevation is 0, but should be 88.26. Any idea why this is happening?

**Comment by patrick-zippenfenig** [comment] 2025-01-29 08:24
This location is an inland lake, with more than 50% of the grid cell covered by water.  

Unfortunately, the system only stores actual elevation for land grid cells, while sea grid cells are masked out with `NaN`. As a result, elevation data is not stored for grid cells with more than 50% water coverage. This approach simplifies filtering out sea grid cells using a single elevation field.  

I had considered using a highly negative number to keep elevation data for sea grid cells. For example, `-1000 = 0 m asl` and `-1088 = 88 m asl`. I’ll create a separate issue ticket and revisit this later.
