### ISSUE TITLE
Error in hourly and 15-minute data

### ISSUE THREAD

**Issue by BlackBird-One** [open-meteo/open-meteo#534] opened 2023-12-02 19:02 UTC
I found an error between the precipitation values in the hourly and 15-minute data. 

The error is that hourly has 0.2 mm or 0.1 mm precipitation and 15-minute precipitation is zero for the whole hour. I think the sum of the 15-minute precipitation must always match the hourly precipitation. 

If the unit of precipitation was mm/sec, this problem would not exist.  

Attached is a graph that shows the error. 

https://api.open-meteo.com/v1/forecast?latitude=50.088&longitude=14.4208&minutely_15=precipitation&hourly=precipitation&start_date=2023-12-01&end_date=2023-12-02

Michal Kus

![image](https://github.com/open-meteo/open-meteo/assets/2879508/87dc2800-d487-4fc9-9459-475ebc4f207f)

**Comment by woheller69** [comment] 2023-12-09 06:06
duplicate of #423 ?

**Comment by patrick-zippenfenig** [comment] 2023-12-11 10:26
Closing in favour of #423

**Closed by patrick-zippenfenig** 2023-12-11 10:26 UTC
