### ISSUE TITLE
[Question] How to avoid getting 0.25 degree wrong coordinates with historical API?

### ISSUE THREAD

**Issue by n-lisichko** [open-meteo/open-meteo#189] opened 2023-01-17 14:42 UTC
Hi!

Thanks for the awesome service!

I'm getting some strange results when requesting data via historical data API:
sometimes the neighboring 'tile' of the grid is returned, relative to what is requested.

For example, if I request data for the point with coordinates 48.75N 71.75E, I get the same coordinates in the response. But if I request data for 43.5N 69E - I get data for 43.75N 68.75E back. Or 49.5,84 for 49.75,84.25, and so on.

Same thing happens with ERA5-Land selected, (except for the 0.1° error step instead of 0.25°).

What am I doing wrong and how can I avoid this?

**Comment by patrick-zippenfenig** [comment] 2023-01-17 17:15
Hi, thanks for asking!

This is most likely caused by the terrain downscaling using and elevation model to fit the best grid-cell. Usually this improves accuracy.

I could add an option to the URL to disable elevation downscale correction and always use the nearest neighbour gird-cell. Wdyt?

**Comment by n-lisichko** [comment] 2023-01-17 17:36
Thanks for the reply!

Is it possible to read a bit more about this feature, to understand its logic better?
And I guess it would be useful to be able to disable this feature, but I'm not sure I'm right here. Maybe I just need to understand how it works.

**Comment by douglasdennis** [comment] 2023-01-19 17:06
@patrick-zippenfenig  I would like to request an option to disable this feature. The elevation model appears to be causing issues on my project.

**Comment by patrick-zippenfenig** [comment] 2023-01-25 11:32
In general, using raw/uncorrected data is a bad idea. A nearest neighbour grid-cell selection may select a grid-cell with sea properties for cities close to the sea. This results in flat temperature readings and higher wind-speeds. A grid-cell with higher elevation in mountainous terrain should not be used for a town in a valley. I can understand however that sometimes using raw data is required.

I have added a parameter `cell_selection` in commit https://github.com/open-meteo/open-meteo/commit/2210b9f4cffa7d0c64ec1627c21c12fbab5ea052 to select between `land`, `sea` and `nearest`. The default `land` will use the old behaviour to select a grid-cell with suitable elevation on land.


With commit https://github.com/open-meteo/open-meteo/commit/cb7234697e45426e0d4963f978a14887dab3ff23, I added a new attribute `elevation_raw`, but I decided to revert it. It adds unnecessary confusion for many users without real value. Instead you can now set `&elevation=nan` to disable statistical downscaling and the API will return the grid-cell elevation (https://github.com/open-meteo/open-meteo/commit/15e6471cee721e258813ec5ca8bdcf362fd5e472). This is also useful to make sure to get raw data without any temperature bias corrections.


Both changes will go live in the next days. Documentation has also been updated.

**Comment by n-lisichko** [comment] 2023-01-25 13:01
Sorry for being not very bright, but may I clarify a few things:

1. There are two correction processes? One to select the most appropriate grid-cell and another to apply corrections based on the point elevation?

2. Do I understand it right: if elevation=nan is not set, API applies temperature correction to different points within the same grid-cell? So if one requests data for the points that fall in one cell, but have different elevation based on the DEM, there will be different temperature data?

Thanks!

**Comment by n-lisichko** [comment] 2023-01-26 15:11
Thanks for the explanation!

And I already see these parameters in the API documentation now, but get "Value of type 'GridSelectionMode' required for key 'cell_selection'." error trying anything (land, nearest, sea) with cell_selection.

Setting elevation=nan doesn't trigger any errors.

Is it just too early to try that?

**Comment by patrick-zippenfenig** [comment] 2023-01-26 15:38
Ups, fixed now. I just deployed it a couple of hours ago without testing it yet.

https://archive-api.open-meteo.com/v1/archive?latitude=52.52&longitude=13.41&start_date=2022-12-23&end_date=2023-01-21&hourly=temperature_2m&cell_selection=nearest&elevation=nan

**Comment by patrick-zippenfenig** [comment] 2023-04-05 10:19
Closing for cleanup. Feel free to reopen if you have more questions

**Closed by patrick-zippenfenig** 2023-04-05 10:19 UTC
Labels: question
