### ISSUE TITLE
please reactivate Flood api ensemble "mean" prediction

### ISSUE THREAD

**Issue by resident12** [open-meteo/open-meteo#322] opened 2023-05-08 14:55 UTC
Please reactivate Flood api ensemble "mean" prediction. The actual output value is "null"

**Comment by resident12** [comment] 2023-05-08 15:00
btw what's is the meaning of the "discharge" vs the "mean" values?

**Comment by resident12** [comment] 2023-05-08 17:52
Bug: the statistical probability values are also available on the consolidated historical data while they should be available on the forecast only.

**Comment by patrick-zippenfenig** [comment] 2023-05-09 09:40
Mean values are fixed now!

> Bug: the statistical probability values are also available on the consolidated historical data while they should be available on the forecast only.

I cannot reproduce this anymore. It hope the previous bug fix solved it. http://localhost:5173/en/docs/flood-api#latitude=59.91&longitude=10.75&daily=river_discharge,river_discharge_mean&models=consolidated_v3&start_date=2022-03-01&end_date=2023-05-01

**Closed by patrick-zippenfenig** 2023-05-09 09:40 UTC
