### ISSUE TITLE
Missing values in `weather_code` and `cloud_cover` ECMWF history for 2017-01-01T00:00

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#1118] opened 2024-11-14 11:41 UTC
Hi,

I've faced an inconsistency in historical data of ECMWF model that is probably a bug. Steps to reproduce are as follows:
- open https://archive-api.open-meteo.com/v1/archive?latitude=48.898064&longitude=50.65346&start_date=2017-01-01&end_date=2017-01-31&hourly=temperature_2m,weather_code,cloud_cover&models=ecmwf_ifs
- look at `temperature_2m` sequence. The first item corresponding to 2017-01-01T00:00 timestamp is not empty;
- look at `weather_code` and `cloud_cover` sequences. The first items are empty;
- check this with other lat/lon paris to ensure that the problem is still present.

I'm not sure whether the `temperature_2m` behaviour or `weather_code` / `cloud_cover` behaviour is correct. Anyway, this mismatch looks strange. Probably this issue needs to be fixed, and if it's a bug indeed, I'll be glad if it's resolved.

Thanks in advance,

Pavel

**Comment by patrick-zippenfenig** [comment] 2024-11-15 08:48
Thanks for the report. The issue is now fixed.

**Closed by patrick-zippenfenig** 2024-11-15 08:48 UTC
