### ISSUE TITLE
Missing `weather_code` and `cloud_cover` in ECMWF History for October 12–16, 2024

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#1135] opened 2024-11-27 11:48 UTC
Hi,

I've found a gap in `weather_code` and `cloud_cover` variables of History API (ECMWF model) with a duration of several days. 

Here are the steps to reproduce the problem:
- open https://archive-api.open-meteo.com/v1/archive?latitude=55&longitude=37.6&start_date=2024-10-08&end_date=2024-10-31&hourly=temperature_2m,relative_humidity_2m,rain,weather_code,surface_pressure,cloud_cover,wind_speed_10m,wind_direction_10m,soil_temperature_0_to_7cm,soil_moisture_0_to_7cm&models=ecmwf_ifs
- look at `weather_code` and `cloud_cover` sequences with indices starting from 97 and ending with 192;
- expected numbers, got nulls;
- changing lat/lon does not affect the result: missing values are still present.

Hope that this issue is easy to be resolved and will be glad if it is fixed soon.

With regards,

Pavel

**Comment by patrick-zippenfenig** [comment] 2024-11-29 11:53
Thanks for the report. The issue is now fixed. Cloud cover total was just recently added on customer request. Before it was computed from low/mid/high cloud cover.

**Closed by patrick-zippenfenig** 2024-11-29 11:53 UTC
